use_frameworks!

platform :ios, '12.2'

target 'Sandbox' do
  # Dev mode
  pod 'IdentitySdkCore', :path => '../IdentitySdkCore.podspec'
  pod 'IdentitySdkWebView', :path => '../IdentitySdkWebView.podspec'
  pod 'IdentitySdkGoogle', :path => '../IdentitySdkGoogle.podspec'
  pod 'IdentitySdkFacebook', :path => '../IdentitySdkFacebook.podspec'

  
end
