use_frameworks!

platform :ios, '13.0'

target 'IdentitySdkFacebook' do
  pod 'IdentitySdkCore', :path => '../IdentitySdkCore.podspec'
  pod 'FBSDKCoreKit', '~> 13'
  pod 'FBSDKLoginKit', '~> 13'
end
