# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2.1
jobs:
  build:
    macos:
      xcode: "11.1.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: |
          cd IdentitySdkCore
          pod install
          cd ../
          pod spec lint IdentitySdkCore.podspec
          # xcodebuild -workspace IdentitySdkCore.xcworkspace -scheme "IdentitySdkCore" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
      - run: |
          cd IdentitySdkFacebook
          pod install
          cd ../
          pod spec lint IdentitySdkFacebook.podspec
          # xcodebuild -workspace IdentitySdkFacebook.xcworkspace -scheme "IdentitySdkFacebook" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
      - run: |
          cd IdentitySdkGoogle
          pod install
          cd ../
          pod spec lint IdentitySdkGoogle.podspec
          # xcodebuild -workspace IdentitySdkGoogle.xcworkspace -scheme "IdentitySdkGoogle" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
      - run: |
          cd IdentitySdkWebView
          pod install
          cd ../
          pod spec lint IdentitySdkWebView.podspec
          #xcodebuild -workspace IdentitySdkWebView.xcworkspace -scheme "IdentitySdkWebView" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
  publish:
    macos:
      xcode: "11.1.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: pod trunk push IdentitySdkCore.podspec
      - run: pod trunk push IdentitySdkFacebook.podspec
      - run: pod trunk push IdentitySdkGoogle.podspec
      - run: pod trunk push IdentitySdkWebView.podspec
  build-sandbox:
    macos:
      xcode: "11.1.0"
    working_directory: ~/repo/Sandbox
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install CocoaPods
          command: curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: pod install
      - run: fastlane scan

default_workflows_filters: &default_workflows_filters
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

default_workflows_tags: &default_workflows_tags
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          <<: *default_workflows_tags
      - publish:
          requires:
            - build
          <<: *default_workflows_filters

